TRACKED_COMPANIES = {
    "AAPL": "Apple Inc.",
    "TSLA": "Tesla Inc.",
    "NVDA": "NVIDIA Corporation",
    "MSFT": "Microsoft Corporation",
    "GOOGL": "Alphabet Inc.",
    "AMZN": "Amazon.com Inc.",
    "META": "Meta Platforms Inc.",
    "PLTR": "Palantir Technologies Inc.",
    "RBLX": "Roblox Corporation",
    "ROKU": "Roku Inc.",
    "SNAP": "Snap Inc.",
    "SQ": "Square Inc.",
    "TWTR": "Twitter Inc.",
    "UBER": "Uber Technologies Inc.",
    "WMT": "Walmart Inc.",
    "X": "Twitter Inc.",
    "ZM": "Zoom Video Communications Inc.",
}