TRACKED_COMPANIES = {
    "AAPL": "Apple Inc.",
    "ACHR": "Arch Resources Inc.",
    "AMD": "Advanced Micro Devices Inc.",
    "AMZN": "Amazon.com Inc.",
    "BABA": "Alibaba Group Holding Limited",
    "GOOGL": "Alphabet Inc.",
    "HOOD": "Robinhood Markets Inc.",
    "JOBY": "Joby Aviation Inc.",
    "LLY": "Eli Lilly and Company",
    "LULU": "Lululemon Athletica Inc.",
    "META": "Meta Platforms Inc.",
    "MSFT": "Microsoft Corporation",
    "NFLX": "Netflix Inc.",
    "NKE": "Nike Inc.",
    "NVDA": "NVIDIA Corporation",
    "OPEN": "Opendoor Technologies Inc.",
    "PLTR": "Palantir Technologies Inc.",
    "ORCL": "Oracle Corporation",
    "QQQ": "Invesco QQQ Trust",
    "QUBT": "Quantum Computing Inc.",
    "RBLX": "Roblox Corporation",
    "RKLB": "Rocket Lab Corporation",
    "ROKU": "Roku Inc.",
    "SNAP": "Snap Inc.",
    "SNDK": "Sandisk Corporation",
    "SQ": "Square Inc.",
    "TSLA": "Tesla Inc.",
    "TWTR": "Twitter Inc.",
    "UBER": "Uber Technologies Inc.",
    "WMT": "Walmart Inc.",
    "ZM": "Zoom Video Communications Inc.",
}