TRACKED_COMPANIES = {
    "AAPL": "Apple Inc.",
    "AMD": "Advanced Micro Devices Inc.",
    "AMZN": "Amazon.com Inc.",
    "BABA": "Alibaba Group Holding Limited",
    "GOOGL": "Alphabet Inc.",
    "META": "Meta Platforms Inc.",
    "MSFT": "Microsoft Corporation",
    "NFLX": "Netflix Inc.",
    "NKE": "Nike Inc.",
    "NVDA": "NVIDIA Corporation",
    "PLTR": "Palantir Technologies Inc.",
    "QQQ": "Invesco QQQ Trust",
    "RBLX": "Roblox Corporation",
    "RKLB": "Rocket Lab Corporation",
    "ROKU": "Roku Inc.",
    "SNAP": "Snap Inc.",
    "SQ": "Square Inc.",
    "TSLA": "Tesla Inc.",
    "TWTR": "Twitter Inc.",
    "UBER": "Uber Technologies Inc.",
    "WMT": "Walmart Inc.",
    "X": "Twitter Inc.",
    "ZM": "Zoom Video Communications Inc.",
}