-- Create daily_highlights table to store historical daily summaries
CREATE TABLE IF NOT EXISTS daily_highlights (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Summary metadata
    summary_date DATE NOT NULL,
    summary_time TIME NOT NULL,
    from_time TIMESTAMP NOT NULL,
    to_time TIMESTAMP NOT NULL,

    -- Summary content
    highlight_text TEXT NOT NULL,
    news_count INTEGER NOT NULL DEFAULT 0,

    -- Categories included in summary
    categories_included TEXT[] DEFAULT '{}',

    -- Timestamps
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),

    -- Unique constraint: one summary per date+time
    CONSTRAINT unique_daily_highlight UNIQUE (summary_date, summary_time)
);

-- Create indexes for efficient queries
CREATE INDEX IF NOT EXISTS idx_daily_highlights_date
ON daily_highlights(summary_date DESC);

CREATE INDEX IF NOT EXISTS idx_daily_highlights_created
ON daily_highlights(created_at DESC);

-- Add comments
COMMENT ON TABLE daily_highlights IS 'Historical daily news summaries generated by LLM';
COMMENT ON COLUMN daily_highlights.summary_date IS 'Date of the summary (EST)';
COMMENT ON COLUMN daily_highlights.summary_time IS 'Time of the summary (EST)';
COMMENT ON COLUMN daily_highlights.from_time IS 'Start of news window (6PM EST previous day)';
COMMENT ON COLUMN daily_highlights.to_time IS 'End of news window (summary_time EST)';
COMMENT ON COLUMN daily_highlights.highlight_text IS 'LLM-generated daily highlight summary';
COMMENT ON COLUMN daily_highlights.news_count IS 'Number of news articles included in summary';
COMMENT ON COLUMN daily_highlights.categories_included IS 'Categories of news included (excludes MACRO_NOBODY)';
